export const offersData = [
  {
    id: 1,
    title: "Столичне місто",
    yield: "15%",
    period: "1 рік",
    risks: "5%",
    totalPrice: "від $62150",
    pricePerSqMeter: "від $1599/м",
    img: "https://drive.google.com/file/d/1F_WeOGoPYW_0Xl5S0NweMrtCiP_1FwaX/view?usp=sharing",
  },
  {
    id: 2,
    title: "Європейський",
    yield: "18%",
    period: "3 роки",
    risks: "7%",
    totalPrice: "від $65855",
    pricePerSqMeter: "від $1650/м",
    img: "https://drive.google.com/file/d/1FXMwcW7s7u5CkRInC8sdmFqM3E1r9xUz/view?usp=sharing",
  },
  {
    id: 3,
    title: "Комфорт Сіті",
    yield: "14%",
    period: "2 роки",
    risks: "10%",
    totalPrice: "від $57990",
    pricePerSqMeter: "від $1410/м",
    img: "https://drive.google.com/file/d/1FUnCeZYtaRO4yprJqQZ8GcRW3IZAsnS9/view?usp=sharing",
  },
  {
    id: 4,
    title: "Business class",
    yield: "18%",
    period: "3 роки",
    risks: "7%",
    totalPrice: "від $95650",
    pricePerSqMeter: "від $2500/м",
    img: "https://drive.google.com/file/d/1Fdwq6MXeqXysNkkeSBXiGRNk6ldm4U1_/view?usp=sharing",
  },
];
