import BestOffers from "@/components/BestOffers";
import Main from "@/components/Main";
import Promo from "@/components/Promo";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Imovito - платформа для инвестиций в недвижимость</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
      <BestOffers />
      <Promo />
    </>
  );
}
